### ISSUE TITLE
Template expansion does not work with symbolized hashes in 2.8.1

### ISSUE THREAD

**Issue by nicolaa** [sporkmonger/addressable#501]
See this sample code in console:
```
> require "addressable/template"
 => true 
3.2.1 :002 > template = Addressable::Template.new("http://example.com/{?query*}")
 => #<Addressable::Template:0x12fac PATTERN:http://example.com/{?query*}> 
3.2.1 :003 > template.expand({"query" => {'foo' => 'bar', 'color' => 'red'}})
 => #<Addressable::URI:0x1d9d4 URI:http://example.com/?foo=bar&color=red> 
3.2.1 :004 > template.expand({query: {foo: "bar", color: "red"}})
rvm/gems/ruby-3.2.1/gems/addressable-2.8.2/lib/addressable/template.rb:900:in `normalize_value': undefined method `to_str' for :foo:Symbol (NoMethodError)

        value = value.respond_to?(:to_ary) ? value.to_ary : value.to_str
                                                                 ^^^^^^^
Did you mean?  to_s
               to_sym
```

**Comment by dentarg** [comment]
This has been reported https://github.com/sporkmonger/addressable/issues/498 and addressed (but not yet released)

Closing as duplicate
