### ISSUE TITLE
 undefined method `to_str' for :id:Symbol (NoMethodError) in 2.8.2

### ISSUE THREAD

**Issue by johrstrom** [sporkmonger/addressable#498]
Hi, I'm getting this error when I've updated to `2.8.2` from `2.8.1`.   Here's a very simple test case in `irb` that I've confirmed works in `2.8.1`. 

```irb
irb(main):004:0> uri = Addressable::Template.new("https://example/some/api/{?query*}")
=> #<Addressable::Template:0x104 PATTERN:https://example/some/api/{?query*}>
irb(main):005:0> uri.expand({'query' => {id: 'abc123' } })
/home/jeff/.gems/ruby-3.0.3/gems/addressable-2.8.2/lib/addressable/template.rb:900:in `normalize_value': undefined method `to_str' for :id:Symbol (NoMethodError)
Did you mean?  to_se-2.8.2.gem
               to_symx-5.0.1.gem
Successffrom /home/jeff/.gems/ruby-3.0.3/gems/addressable-2.8.2/lib/addressable/template.rb:908:in `block in normalize_value'
Successffrom /home/jeff/.gems/ruby-3.0.3/gems/addressable-2.8.2/lib/addressable/template.rb:907:in `each'
Parsing from /home/jeff/.gems/ruby-3.0.3/gems/addressable-2.8.2/lib/addressable/template.rb:907:in `inject'
Installifrom /home/jeff/.gems/ruby-3.0.3/gems/addressable-2.8.2/lib/addressable/template.rb:907:in `normalize_value'
Parsing from /home/jeff/.gems/ruby-3.0.3/gems/addressable-2.8.2/lib/addressable/template.rb:774:in `block in transform_capture'
Installifrom /home/jeff/.gems/ruby-3.0.3/gems/addressable-2.8.2/lib/addressable/template.rb:756:in `each'
Done insfrom /home/jeff/.gems/ruby-3.0.3/gems/addressable-2.8.2/lib/addressable/template.rb:756:in `inject'
2 gems ifrom /home/jeff/.gems/ruby-3.0.3/gems/addressable-2.8.2/lib/addressable/template.rb:756:in `transform_capture'
[dashboafrom /home/jeff/.gems/ruby-3.0.3/gems/addressable-2.8.2/lib/addressable/template.rb:595:in `block in expand'
irb(mainfrom /home/jeff/.gems/ruby-3.0.3/gems/addressable-2.8.2/lib/addressable/template.rb:594:in `gsub!'
=> true from /home/jeff/.gems/ruby-3.0.3/gems/addressable-2.8.2/lib/addressable/template.rb:594:in `expand'
irb(mainfrom (irb):5:in `<main>'mplate.new("#{server[:host]}{/segments*}/{?query*}")
        from /home/jeff/apps/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/irb-1.3.5/exe/irb:11:in `<top (required)>'
        from /home/jeff/apps/ruby/3.0.3/bin/irb:23:in `load'
        from /home/jeff/apps/ruby/3.0.3/bin/irb:23:in `<main>'
```

Here's a simple snippet that you may be able to just copy paste easier.
```ruby
require 'addressable'

uri = Addressable::Template.new("https://example/some/api/{?query*}")
uri.expand({'query' => { id: 'abc123' }})
```

**Comment by johrstrom** [comment]
Obviously it's due to passing a hash with symbol keys instead of string keys. Just using string keys works, in case other folks run into this and need a work around.

```ruby
require 'addressable'

uri = Addressable::Template.new("https://example/some/api/{?query*}")
uri.expand({'query' => { 'id' => 'abc123' } })
```

**Comment by dentarg** [comment]
@jarthod mind taking a look?

I guess the template tests does not use symbols?

**Comment by johrstrom** [comment]
I was also able to reproduce with integers as values, so I think it affects keys and values, just FYI.

```
require 'addressable'

uri = Addressable::Template.new("https://example/some/api/{?query*}")
uri.expand({'query' => { 'id' => 1 }})
```

**Comment by dentarg** [comment]
Looks like `to_s` was always called before https://github.com/sporkmonger/addressable/pull/492 (https://github.com/sporkmonger/addressable/pull/492/files#diff-fb36d3dc67e6565ffde17e666a98697f48e76dac38fabf1bb9e97cdf3b583d76)

https://github.com/sporkmonger/addressable/blob/ab4bc464027d9edc4aee410f20895483b107b3cd/lib/addressable/idna/pure.rb#L115-L117

https://github.com/sporkmonger/addressable/blob/ab4bc464027d9edc4aee410f20895483b107b3cd/lib/addressable/idna/native.rb#L32-L34

**Comment by johrstrom** [comment]
I can submit a patch if here you like, though given it's worked for the past 11 years, I'm not sure what unintended side affects it may cause. Someone with more intimate knowledge of the callers may know more?

https://github.com/sporkmonger/addressable/blob/bcaf766b0a91d889d0a0bfc5cfbdc07bd376924b/lib/addressable/template.rb#L900

**Comment by jarthod** [comment]
I am having a look, I saw specs checking both symbols, string, and integers so I thought this was covered but apparently they were only testing this at the first level, and it turns out there's a special treatment at this level, so I'll add a couple more specs testing this at the second level and provide a patch. From what I can see putting back a `to_s` at the right place will do the trick yes.

**Comment by crevete** [comment]
@dentarg just want to know when the 2.8.3 tag will be cut? thanks

**Comment by dentarg** [comment]
2.8.3 is out now
