### ISSUE TITLE
Addressable does not work on Ruby 1.8.5

### ISSUE THREAD

**Issue by jamtur01** [sporkmonger/addressable#70]
On Ruby 1.8.5 the `instance_variable_defined?' method does not exist and addressable/uri uses this method. Hence on Ruby 1.8.5 you get:

undefined method `instance_variable_defined?' for #Addressable::URI:0xb6c9cdfc
